<?php

/**
 * @file
 * A QA Workflow
 *
 */

define('ISLANDORA_QA_STATUS__NOT_DONE', 0);
define('ISLANDORA_QA_STATUS__DONE', 1);
define('ISLANDORA_QA_STATUS__REJECTED', 2);

/**
 * Implements hook_menu().
 */
function islandora_qa_menu() {
  $items = array();

  $items['admin/islandora/tools/qa'] = array(
    'title' => 'Islandora QA',
    'description' => 'Setup a workflow for QA',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_qa_create_form'),
    'file' => 'includes/create.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['islandora_qa/task/%'] = array(
    'title' => 'Task @item',
    'title arguments' => array('@item' => 2),
    'page callback' => 'islandora_qa_task_page_callback',
    'page arguments' => array(2),
    'access callback' => 'islandora_qa_task_access',
    'file' => 'includes/tasks.inc',
  );
  
  $items['islandora_qa/task/%/reject/%'] = array(
    'title' => 'Reject @item',
    'title arguments' => array('@item' => 4),
    'page callback' => 'islandora_qa_task_reject_page_callback',
    'page arguments' => array(2,4),
    'access callback' => 'islandora_qa_task_access',
    'file' => 'includes/tasks.inc',
  );
  
  return $items;
}


/**
 * Implements hook_admin_paths_alter().
 */
function islandora_qa_admin_paths_alter(&$paths) {
    $paths['islandora_qa/task/*'] = TRUE;
}

/**
 * Check permissions for an set.
 *
 * Just returns True
 * TODO: Sometimes return false
 * 
 */
function islandora_qa_task_access() {
  return true;
}

/**
 * Implements hook_views_api().
 */
function islandora_qa_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'islandora_qa') . '/views',
  );
}
